# Generated by Django 4.1.5 on 2023-01-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('url', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('sample_content', models.TextField(max_length=250)),
            ],
        ),
    ]
